version: "3"
services:
  tests:
    image: todotests    
    depends_on:
      - back
      - front
    environment:
      - FRONT_HOST=front
  front:
    image: todofrontend    
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_HOST=back
      - REACT_APP_API_HOST=3001
    depends_on:
      - back
  back:
    image: todobackend    
    ports:
      - 3001:3001
