version: "3"
services:
  todotests:
    image: todotests    
    depends_on:
      - "back"
      - "front"
    environment:
      - FRONT_HOST=front      
  front:
    image: todofrontend      
    environment:
      - REACT_APP_API_HOST=back      
    depends_on:
      - "back"
    ports:
      - 3000:3000
  back:
    image: todobackend  
    ports:
      - 3001:3001
